module.exports = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SETCATEGORY: "SETCATEGORY",
  RESETCATEGORY: "RESETCATEGORY",
  ACTIVE_PERSON_DROPDOWN: "ACTIVE_PERSON_DROPDOWN",
  DEACTIVE_PERSON_DROPDOWN: "DEACTIVE_PERSON_DROPDOWN",
  ACTIVE_DROPDOWN: "ACTIVE_DROPDOWN",
  DEACTIVE_DROPDOWN: "DEACTIVE_DROPDOWN",
  SET_DATE: "SET_DATE",
  SET_TIME: "SET_TIME",
  SET_SHOW: "SET_SHOW",
  SET_SHOW_DONE: "SET_SHOW_DONE",
  SET_STEP: "SET_STEP"
};
