module.exports = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SETCATEGORY: "SETCATEGORY",
  RESETCATEGORY: "RESETCATEGORY",
  ACTIVE_PERSON_DROPDOWN: "ACTIVE_PERSON_DROPDOWN",
  DEACTIVE_PERSON_DROPDOWN: "DEACTIVE_PERSON_DROPDOWN",
  ACTIVE_DROPDOWN: "ACTIVE_DROPDOWN",
  DEACTIVE_DROPDOWN: "DEACTIVE_DROPDOWN",
};
